// src/components/modules/PlaygroundModule.tsx
import { useState, useEffect } from 'react'
import { useProviderStore } from '@/stores/providerStore'
import PlaygroundApp from '../playground/PlaygroundApp'
import SystemPromptModal from './optimize/components/quick/SystemPromptModal'

const STORAGE_KEY = 'yprompt_playground_system_prompt'

export default function PlaygroundModule() {
  const providerStore = useProviderStore()
  const [systemPrompt, setSystemPrompt] = useState('')
  const [systemPromptDraft, setSystemPromptDraft] = useState('')
  const [showSystemPromptModal, setShowSystemPromptModal] = useState(false)

  // 初始化 providerStore
  useEffect(() => {
    if (!providerStore.isInitialized) {
      providerStore.initialize()
    }
  }, [providerStore])

  // 从 localStorage 加载系统提示词
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY)
      if (saved) {
        setSystemPrompt(saved)
      }
    } catch (error) {
      console.warn('加载系统提示词失败', error)
    }
  }, [])

  // 保存系统提示词到 localStorage
  useEffect(() => {
    if (systemPrompt) {
      localStorage.setItem(STORAGE_KEY, systemPrompt)
    }
  }, [systemPrompt])

  const openSystemPromptModal = () => {
    setSystemPromptDraft(systemPrompt)
    setShowSystemPromptModal(true)
  }

  const handleSystemPromptSave = () => {
    setSystemPrompt(systemPromptDraft)
    setShowSystemPromptModal(false)
  }

  return (
    <div className="w-full flex-1 flex flex-col overflow-hidden p-2 playground-container min-h-0">
      {showSystemPromptModal && (
        <SystemPromptModal
          isOpen={showSystemPromptModal}
          modelValue={systemPromptDraft}
          onUpdateModelValue={setSystemPromptDraft}
          onClose={() => setShowSystemPromptModal(false)}
          onSave={handleSystemPromptSave}
        />
      )}

      <div className="bg-white rounded-lg shadow-sm p-4 mb-4 flex-shrink-0">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="min-w-0">
            <h2 className="text-xl lg:text-2xl font-bold text-gray-900">提示词操练场</h2>
            <p className="text-sm text-gray-500">实时调试提示词、网页、图表与可视化 Artifact</p>
          </div>
        </div>
      </div>

      <div className="flex-1 min-h-0 overflow-hidden">
        <PlaygroundApp systemPrompt={systemPrompt} onOpenSystemPrompt={openSystemPromptModal} />
      </div>
    </div>
  )
}

// src/components/modules/PlaygroundModule.vue
<template>
  <div class="w-full h-full flex flex-col overflow-hidden p-2 playground-container">
      <SystemPromptModal
      :is-open="showSystemPromptModal"
      v-model="systemPromptDraft"
      :title="'设置系统提示词'"
      @close="showSystemPromptModal = false"
      @save="handleSystemPromptSave"
    />

    <div class="bg-white rounded-lg shadow-sm p-4 mb-4 flex-shrink-0">
      <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div class="min-w-0">
          <h2 class="text-xl lg:text-2xl font-bold text-gray-900">提示词操练场</h2>
          <p class="text-sm text-gray-500">实时调试提示词、网页、图表与可视化 Artifact</p>
        </div>
      </div>
    </div>

    <div class="flex-1 min-h-0 overflow-hidden">
      <PlaygroundApp
        :system-prompt="systemPrompt"
        @open-system-prompt="openSystemPromptModal"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import PlaygroundApp from '@/components/playground/PlaygroundApp.js'
import SystemPromptModal from '@/components/modules/optimize/components/SystemPromptModal.vue'
import '@/utils/playgroundGlobals'
import '@/style/playground.css'
import { useProviderStore } from '@/stores/providerStore'

const providerStore = useProviderStore()

// 初始化 providerStore
onMounted(async () => {
  // 如果还没有初始化，则初始化
  if (!providerStore.isInitialized) {
    await providerStore.initialize()
  }
})

const STORAGE_KEY = 'yprompt_playground_system_prompt'
const systemPrompt = ref('')
const systemPromptDraft = ref('')
const showSystemPromptModal = ref(false)

if (typeof window !== 'undefined') {
  try {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved) {
      systemPrompt.value = saved
    }
  } catch (error) {
    console.warn('加载系统提示词失败', error)
  }
}

watch(systemPrompt, (value) => {
  if (typeof window === 'undefined') return
  localStorage.setItem(STORAGE_KEY, value)
})

const openSystemPromptModal = () => {
  systemPromptDraft.value = systemPrompt.value
  showSystemPromptModal.value = true
}

const handleSystemPromptSave = () => {
  systemPrompt.value = systemPromptDraft.value
}
</script>
