// src/views/LoginView.tsx
import { useState, useEffect } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Eye, EyeOff, AlertCircle, Loader2 } from 'lucide-react'
import { useAuthStore } from '@/stores/authStore'
import { isDebugMode as checkDebugMode } from '@/services/mockApiService'

export default function LoginView() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  // 使用选择器避免不必要的重渲染
  const getAuthConfig = useAuthStore((state) => state.getAuthConfig)
  const loginWithPassword = useAuthStore((state) => state.loginWithPassword)
  const token = useAuthStore((state) => state.token)
  const user = useAuthStore((state) => state.user)
  
  const isDebugMode = checkDebugMode()
  
  const [authConfig, setAuthConfig] = useState({
    local_auth_enabled: true
  })
  
  const [loginForm, setLoginForm] = useState({
    password: ''
  })
  
  const [isLoading, setIsLoading] = useState(true)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [rememberMe, setRememberMe] = useState(true)
  
  const [loginErrors, setLoginErrors] = useState<{
    password?: string
  }>({})
  
  const validatePassword = (password: string): string | null => {
    if (!password) return '请输入密码'
    return null
  }
  
  const validateLoginForm = () => {
    const errors: { password?: string } = {}
    const passwordError = validatePassword(loginForm.password)
    
    if (passwordError) errors.password = passwordError
    
    setLoginErrors(errors)
    return Object.keys(errors).length === 0
  }
  
  const clearFieldError = (field: 'password') => {
    if (loginErrors[field]) {
      setLoginErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors[field]
        return newErrors
      })
    }
  }
  
  const isLoginFormValid = loginForm.password.length > 0 && Object.keys(loginErrors).length === 0
  
  const fetchAuthConfig = async () => {
    try {
      const config = await getAuthConfig()
      if (config) {
        setAuthConfig(config)
      }
    } catch (error) {
      console.error('获取认证配置失败:', error)
    } finally {
      setIsLoading(false)
    }
  }
  
  const saveRememberMe = () => {
    if (rememberMe) {
      localStorage.setItem('yprompt_remember_me', 'true')
    } else {
      localStorage.removeItem('yprompt_remember_me')
    }
  }
  
  const handleLocalLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!validateLoginForm()) {
      return
    }
    
    setErrorMessage('')
    setIsSubmitting(true)
    
    try {
      const result = await loginWithPassword(
        'admin',  // 固定用户名
        loginForm.password
      )
      
      if (result.success) {
        saveRememberMe()
        // 登录成功后立即跳转
        const redirect = searchParams.get('redirect')
        if (redirect && redirect !== '/login') {
          navigate(redirect, { replace: true })
        } else {
          navigate('/generate', { replace: true })
        }
      } else {
        setErrorMessage(result.message || '密码错误')
      }
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : '登录失败，请稍后重试')
      console.error('登录失败:', error)
    } finally {
      setIsSubmitting(false)
    }
  }
  
  useEffect(() => {
    const isLoggedIn = !!token && !!user
    if (isLoggedIn) {
      navigate('/generate', { replace: true })
      return
    }
    
    const savedRememberMe = localStorage.getItem('yprompt_remember_me')
    if (savedRememberMe === 'true') {
      setRememberMe(true)
    }
    
    fetchAuthConfig()
  }, [token, user, navigate])
  
  return (
    <div className="login-container min-h-screen flex items-center justify-center bg-gradient-to-br from-[#667eea] to-[#764ba2] p-5 relative overflow-hidden">
      <div className="login-container-bg absolute -top-1/2 -left-1/2 w-[200%] h-[200%] bg-[radial-gradient(circle,rgba(255,255,255,0.1)_1px,transparent_1px)] bg-[length:50px_50px] animate-[float_20s_linear_infinite] pointer-events-none" />
      
      <div className="login-card bg-white rounded-2xl shadow-[0_20px_60px_rgba(0,0,0,0.15)] w-full max-w-[420px] p-10 relative z-10 animate-[slideUp_0.4s_ease-out]">
        {/* Logo和标题 */}
        <div className="login-header text-center mb-8">
          <div className="logo-wrapper mb-4 flex justify-center">
            <div className="logo-icon w-16 h-16 bg-gradient-to-br from-[#667eea] to-[#764ba2] rounded-2xl flex items-center justify-center text-white text-2xl font-bold shadow-[0_4px_12px_rgba(102,126,234,0.3)]">
              YP
            </div>
          </div>
          <h1 className="login-title text-[32px] font-bold text-[#1a202c] m-0 mb-2 tracking-tight">
            YPrompt
          </h1>
          <p className="login-subtitle text-sm text-[#718096] m-0">
            提示词管理系统
          </p>
          {/* Debug 模式提示 */}
          {isDebugMode && (
            <div className="debug-badge inline-flex items-center gap-1.5 mt-3 px-3 py-1.5 bg-[rgba(255,193,7,0.1)] border border-[rgba(255,193,7,0.3)] rounded-lg text-xs text-[#856404] font-medium">
              <span className="debug-icon text-sm">🐛</span>
              <span>Debug 模式（Mock API）</span>
            </div>
          )}
        </div>

        {/* 加载状态 */}
        {isLoading ? (
          <div className="loading-state text-center py-[60px]">
            <div className="loading-spinner w-12 h-12 border-4 border-[#e2e8f0] border-t-[#667eea] rounded-full animate-spin mx-auto mb-4" />
            <p className="loading-text text-[#718096] text-sm">正在加载...</p>
          </div>
        ) : (
          /* 登录表单 */
          <div className="login-content">
            {authConfig.local_auth_enabled && (
              <div className="login-section mb-5">
                <form onSubmit={handleLocalLogin} className="login-form mt-5">
                  {/* 密码 */}
                  <div className="form-group mb-5">
                    <label htmlFor="password" className="block mb-2 text-sm font-medium text-[#4a5568]">
                      密码
                    </label>
                    <div className="input-wrapper relative flex items-center">
                      <input
                        id="password"
                        type={showPassword ? 'text' : 'password'}
                        value={loginForm.password}
                        onChange={(e) => {
                          setLoginForm({ password: e.target.value })
                          clearFieldError('password')
                        }}
                        onBlur={validateLoginForm}
                        className={`form-input w-full px-4 py-3 pr-11 border-2 rounded-lg text-sm transition-all bg-white ${
                          loginErrors.password
                            ? 'border-[#e53e3e] focus:border-[#e53e3e] focus:shadow-[0_0_0_4px_rgba(229,62,62,0.1)]'
                            : 'border-[#e2e8f0] focus:border-[#667eea] focus:shadow-[0_0_0_4px_rgba(102,126,234,0.1)]'
                        } ${isSubmitting ? 'bg-[#f7fafc] cursor-not-allowed opacity-70' : ''}`}
                        placeholder="请输入密码"
                        disabled={isSubmitting}
                        autoComplete="current-password"
                      />
                      <button
                        type="button"
                        className="password-toggle absolute right-3 bg-none border-0 text-[#718096] cursor-pointer p-1 flex items-center justify-center transition-colors hover:text-[#4a5568] disabled:cursor-not-allowed disabled:opacity-50"
                        onClick={() => setShowPassword(!showPassword)}
                        disabled={isSubmitting}
                        tabIndex={-1}
                      >
                        {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                      </button>
                    </div>
                    {loginErrors.password && (
                      <div className="field-error mt-1.5 text-xs text-[#e53e3e] flex items-center gap-1">
                        {loginErrors.password}
                      </div>
                    )}
                  </div>

                  {/* 记住我 */}
                  <div className="form-options flex justify-between items-center mb-5">
                    <label className="checkbox-label flex items-center gap-2 text-sm text-[#4a5568] cursor-pointer select-none">
                      <input
                        type="checkbox"
                        checked={rememberMe}
                        onChange={(e) => setRememberMe(e.target.checked)}
                        className="checkbox-input w-4 h-4 cursor-pointer accent-[#667eea]"
                        disabled={isSubmitting}
                      />
                      <span>记住我</span>
                    </label>
                  </div>

                  {/* 错误提示 */}
                  {errorMessage && (
                    <div className="error-message px-4 py-3 bg-[#fed7d7] text-[#c53030] rounded-lg text-sm mb-4 flex items-center gap-2 border border-[#fc8181] animate-[fade_0.3s_ease]">
                      <AlertCircle size={16} />
                      <span>{errorMessage}</span>
                    </div>
                  )}

                  {/* 登录按钮 */}
                  <button
                    type="submit"
                    className="btn btn-primary btn-block w-full px-6 py-3 rounded-lg text-[15px] font-medium cursor-pointer transition-all inline-flex items-center justify-center gap-2 bg-gradient-to-r from-[#667eea] to-[#764ba2] text-white shadow-[0_4px_12px_rgba(102,126,234,0.3)] hover:translate-y-[-1px] hover:shadow-[0_6px_16px_rgba(102,126,234,0.4)] active:translate-y-0 disabled:opacity-60 disabled:cursor-not-allowed disabled:transform-none"
                    disabled={isSubmitting || !isLoginFormValid}
                  >
                    {isSubmitting ? (
                      <>
                        <Loader2 size={18} className="spinning animate-spin" />
                        <span>登录中...</span>
                      </>
                    ) : (
                      <span>登录</span>
                    )}
                  </button>
                </form>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

// src/views/LoginView.vue
<template>
  <div class="login-container">
    
    <div class="login-card">
      <!-- Logo和标题 -->
      <div class="login-header">
        <div class="logo-wrapper">
          <div class="logo-icon">YP</div>
        </div>
        <h1 class="login-title">YPrompt</h1>
        <p class="login-subtitle">提示词管理系统</p>
        <!-- Debug 模式提示 -->
        <div v-if="isDebugMode" class="debug-badge">
          <span class="debug-icon">🐛</span>
          <span>Debug 模式（Mock API）</span>
        </div>
      </div>

      <!-- 加载状态 -->
      <div v-if="isLoading" class="loading-state">
        <div class="loading-spinner"></div>
        <p class="loading-text">正在加载...</p>
      </div>

      <!-- 登录表单 -->
      <div v-else class="login-content">
        <!-- 本地账号密码登录 -->
        <div v-if="authConfig.local_auth_enabled" class="login-section">
          <form @submit.prevent="handleLocalLogin" class="login-form">
            <!-- 密码 -->
            <div class="form-group">
              <label for="password">密码</label>
              <div class="input-wrapper">
                <input
                  id="password"
                  v-model="loginForm.password"
                  :type="showPassword ? 'text' : 'password'"
                  class="form-input"
                  :class="{ 'input-error': loginErrors.password }"
                  placeholder="请输入密码"
                  :disabled="isSubmitting"
                  autocomplete="current-password"
                  @blur="validateLoginForm"
                  @input="clearFieldError('password')"
                />
                <button
                  type="button"
                  class="password-toggle"
                  @click="showPassword = !showPassword"
                  :disabled="isSubmitting"
                  tabindex="-1"
                >
                  <Eye v-if="!showPassword" :size="18" />
                  <EyeOff v-else :size="18" />
                </button>
              </div>
              <div v-if="loginErrors.password" class="field-error">{{ loginErrors.password }}</div>
            </div>

            <!-- 记住我 -->
            <div class="form-options">
              <label class="checkbox-label">
                <input
                  type="checkbox"
                  v-model="rememberMe"
                  class="checkbox-input"
                  :disabled="isSubmitting"
                />
                <span>记住我</span>
              </label>
            </div>

            <!-- 错误提示 -->
            <Transition name="fade">
              <div v-if="errorMessage" class="error-message">
                <AlertCircle :size="16" />
                <span>{{ errorMessage }}</span>
              </div>
            </Transition>

            <!-- 登录按钮 -->
            <button
              type="submit"
              class="btn btn-primary btn-block"
              :disabled="isSubmitting || !isLoginFormValid"
            >
              <Loader2 v-if="isSubmitting" :size="18" class="spinning" />
              <span v-if="isSubmitting">登录中...</span>
              <span v-else>登录</span>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/authStore'
import { Eye, EyeOff, AlertCircle, Loader2 } from 'lucide-vue-next'
import { isDebugMode as checkDebugMode } from '@/services/mockApiService'

const router = useRouter()
const authStore = useAuthStore()

// Debug 模式状态
const isDebugMode = computed(() => checkDebugMode())

// 认证配置
const authConfig = ref({
  local_auth_enabled: true
})

// 表单数据
const loginForm = ref({
  password: ''
})

// 状态
const isLoading = ref(true)
const isSubmitting = ref(false)
const errorMessage = ref('')
const showPassword = ref(false)
const rememberMe = ref(true) // 默认勾选记住我

// 表单验证错误
const loginErrors = ref<{
  password?: string
}>({})

// 表单验证
const validatePassword = (password: string): string | null => {
  if (!password) return '请输入密码'
  return null
}

const validateLoginForm = () => {
  loginErrors.value = {}
  const passwordError = validatePassword(loginForm.value.password)

  if (passwordError) loginErrors.value.password = passwordError

  return Object.keys(loginErrors.value).length === 0
}

const clearFieldError = (field: 'password') => {
  if (loginErrors.value[field]) {
    delete loginErrors.value[field]
  }
}

// 计算属性：表单是否有效
const isLoginFormValid = computed(() => {
  return loginForm.value.password.length > 0 &&
         Object.keys(loginErrors.value).length === 0
})

// 获取认证配置
const fetchAuthConfig = async () => {
  try {
    const config = await authStore.getAuthConfig()
    if (config) {
      authConfig.value = config
    }
  } catch (error) {
    console.error('获取认证配置失败:', error)
  } finally {
    isLoading.value = false
  }
}

// 保存记住我设置
const saveRememberMe = () => {
  if (rememberMe.value) {
    localStorage.setItem('yprompt_remember_me', 'true')
  } else {
    localStorage.removeItem('yprompt_remember_me')
  }
}

// 本地账号密码登录
const handleLocalLogin = async () => {
  if (!validateLoginForm()) {
    return
  }

  errorMessage.value = ''
  isSubmitting.value = true

  try {
    const result = await authStore.loginWithPassword(
      'admin',  // 固定用户名
      loginForm.value.password
    )

    if (result.success) {
      // 保存记住我设置
      saveRememberMe()
      // 登录成功，跳转到原始目标路径或主页
      const redirect = router.currentRoute.value.query.redirect as string
      if (redirect && redirect !== '/login') {
        router.push(redirect)
      } else {
        router.push('/')
      }
    } else {
      // 显示详细的错误信息
      errorMessage.value = result.message || '密码错误'
    }
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : '登录失败，请稍后重试'
    console.error('登录失败:', error)
  } finally {
    isSubmitting.value = false
  }
}

onMounted(() => {
  // 如果已登录，直接跳转
  if (authStore.isLoggedIn) {
    router.push('/')
    return
  }

  // 恢复记住我状态
  const savedRememberMe = localStorage.getItem('yprompt_remember_me')
  if (savedRememberMe === 'true') {
    rememberMe.value = true
  }

  // 获取认证配置
  fetchAuthConfig()
})
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 20px;
  position: relative;
  overflow: hidden;
}

.login-container::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, rgba(255, 255, 255, 0.1) 1px, transparent 1px);
  background-size: 50px 50px;
  animation: float 20s linear infinite;
  pointer-events: none;
}

@keyframes float {
  0% { transform: translate(0, 0); }
  100% { transform: translate(50px, 50px); }
}

.login-card {
  background: white;
  border-radius: 16px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
  width: 100%;
  max-width: 420px;
  padding: 40px;
  position: relative;
  z-index: 1;
  animation: slideUp 0.4s ease-out;
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.logo-wrapper {
  margin-bottom: 16px;
  display: flex;
  justify-content: center;
}

.logo-icon {
  width: 64px;
  height: 64px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 24px;
  font-weight: 700;
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.login-title {
  font-size: 32px;
  font-weight: 700;
  color: #1a202c;
  margin: 0 0 8px 0;
  letter-spacing: -0.5px;
}

.login-subtitle {
  font-size: 14px;
  color: #718096;
  margin: 0;
}

.debug-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  margin-top: 12px;
  padding: 6px 12px;
  background: rgba(255, 193, 7, 0.1);
  border: 1px solid rgba(255, 193, 7, 0.3);
  border-radius: 8px;
  font-size: 12px;
  color: #856404;
  font-weight: 500;
}

.debug-icon {
  font-size: 14px;
}

.loading-state {
  text-align: center;
  padding: 60px 0;
}

.loading-spinner {
  width: 48px;
  height: 48px;
  border: 4px solid #e2e8f0;
  border-top-color: #667eea;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
  margin: 0 auto 16px;
}

.loading-text {
  color: #718096;
  font-size: 14px;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.login-section {
  margin-bottom: 20px;
}

.login-form {
  margin-top: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-size: 14px;
  font-weight: 500;
  color: #4a5568;
}

.input-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.form-input {
  width: 100%;
  padding: 12px 16px;
  padding-right: 44px;
  border: 2px solid #e2e8f0;
  border-radius: 8px;
  font-size: 14px;
  transition: all 0.2s;
  background: #fff;
}

.form-input:focus {
  outline: none;
  border-color: #667eea;
  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1);
}

.form-input.input-error {
  border-color: #e53e3e;
}

.form-input.input-error:focus {
  border-color: #e53e3e;
  box-shadow: 0 0 0 4px rgba(229, 62, 62, 0.1);
}

.form-input:disabled {
  background: #f7fafc;
  cursor: not-allowed;
  opacity: 0.7;
}

.password-toggle {
  position: absolute;
  right: 12px;
  background: none;
  border: none;
  color: #718096;
  cursor: pointer;
  padding: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: color 0.2s;
  z-index: 1;
}

.password-toggle:hover {
  color: #4a5568;
}

.password-toggle:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.input-icon {
  position: absolute;
  right: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}

.input-icon.success {
  color: #38a169;
}

.field-error {
  margin-top: 6px;
  font-size: 12px;
  color: #e53e3e;
  display: flex;
  align-items: center;
  gap: 4px;
}

.field-hint {
  margin-top: 6px;
  font-size: 12px;
  color: #718096;
}

.form-options {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #4a5568;
  cursor: pointer;
  user-select: none;
}

.checkbox-input {
  width: 16px;
  height: 16px;
  cursor: pointer;
  accent-color: #667eea;
}

.btn {
  padding: 12px 24px;
  border: none;
  border-radius: 8px;
  font-size: 15px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  position: relative;
}

.btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none !important;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.btn-primary:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 6px 16px rgba(102, 126, 234, 0.4);
}

.btn-primary:active:not(:disabled) {
  transform: translateY(0);
}

.btn-block {
  width: 100%;
}

.spinning {
  animation: spin 1s linear infinite;
}

.error-message {
  padding: 12px 16px;
  background: #fed7d7;
  color: #c53030;
  border-radius: 8px;
  font-size: 14px;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 8px;
  border: 1px solid #fc8181;
}


/* 模态框样式 */
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
  backdrop-filter: blur(4px);
}

.modal-content {
  background: white;
  border-radius: 16px;
  width: 100%;
  max-width: 420px;
  max-height: 90vh;
  overflow-y: auto;
  padding: 32px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
  padding-bottom: 16px;
  border-bottom: 1px solid #e2e8f0;
}

.modal-header h2 {
  margin: 0;
  font-size: 22px;
  font-weight: 600;
  color: #1a202c;
}

.modal-close {
  background: none;
  border: none;
  color: #a0aec0;
  cursor: pointer;
  padding: 6px;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  transition: all 0.2s;
}

.modal-close:hover {
  background: #f7fafc;
  color: #4a5568;
}

/* 动画 */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.modal-enter-active,
.modal-leave-active {
  transition: all 0.3s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from .modal-content,
.modal-leave-to .modal-content {
  transform: scale(0.95) translateY(-10px);
}

/* 响应式设计 */
@media (max-width: 640px) {
  .login-container {
    padding: 16px;
  }

  .login-card {
    padding: 32px 24px;
    border-radius: 12px;
  }

  .login-title {
    font-size: 28px;
  }

  .logo-icon {
    width: 56px;
    height: 56px;
    font-size: 20px;
  }

  .modal-content {
    padding: 24px 20px;
    max-height: 95vh;
  }

  .form-input {
    font-size: 16px; /* 防止iOS自动缩放 */
  }
}

@media (max-width: 480px) {
  .login-card {
    padding: 24px 20px;
  }

  .login-title {
    font-size: 24px;
  }

  .login-subtitle {
    font-size: 13px;
  }
}
</style>
