// src/components/ChatInterface.tsx
import { useRef, useEffect } from 'react'
import { Upload } from 'lucide-react'
import { usePromptStore } from '@/stores/promptStore'
import { useChatMessages } from '@/hooks/useChatMessages'
import { useChatInput } from '@/hooks/useChatInput'
import { useChatAttachments } from '@/hooks/useChatAttachments'
import { useChatModel } from '@/hooks/useChatModel'
import { useChatQuickReplies } from '@/hooks/useChatQuickReplies'
import { useChatLogic } from '@/hooks/useChatLogic'
import { useChatMessageOperations } from '@/hooks/useChatMessageOperations'
import ChatHeader from './chat/components/ChatHeader'
import ChatMessageList from './chat/components/ChatMessageList'
import ChatQuickReplies from './chat/components/ChatQuickReplies'
import ChatInputArea from './chat/components/ChatInputArea'

export default function ChatInterface() {
  const inputContainerRef = useRef<HTMLDivElement>(null)
  
  // 使用选择器来避免不必要的重渲染
  const isGenerating = usePromptStore((state) => state.isGenerating)
  const isTyping = usePromptStore((state) => state.isTyping)
  const chatMessagesFromStore = usePromptStore((state) => state.chatMessages)
  
  const chatMessages = useChatMessages()
  const chatInput = useChatInput()
  const chatAttachments = useChatAttachments()
  const chatModel = useChatModel()
  const chatQuickReplies = useChatQuickReplies(inputContainerRef)
  const chatMessageOperations = useChatMessageOperations()
  
  const chatLogic = useChatLogic({
    chatMessages,
    chatModel,
    chatInput,
    chatAttachments,
    chatQuickReplies
  })

  useEffect(() => {
    chatLogic.initializeChat()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []) // 只在组件挂载时初始化一次

  const handleSendMessage = () => {
    if (!chatInput.userInput.trim() && chatAttachments.currentAttachments.length === 0) {
      return
    }
    
    chatLogic.sendMessage(chatInput.userInput)
  }

  const handleInputKeydown = (event: React.KeyboardEvent) => {
    chatInput.handleKeydown(event, handleSendMessage)
  }

  const handleQuickReplySelect = (reply: string) => {
    chatQuickReplies.selectQuickReply(reply, (selectedReply: string) => {
      chatInput.setUserInput(selectedReply)
      handleSendMessage()
    })
  }

  const handleClearChat = () => {
    chatLogic.clearChat()
  }

  const handleInterrupt = () => {
    chatLogic.interruptGeneration()
  }

  const handleRegenerate = (messageId: string, messageIndex: number) => {
    const { provider, model } = chatModel.getCurrentChatModel()
    chatLogic.regenerateMessage(messageId, messageIndex, provider, model)
  }

  const handleResend = (messageId: string, messageIndex: number) => {
    // 处理编辑后的重新发送 - 先保存编辑
    const message = chatMessagesFromStore.find(msg => msg.id === messageId)
    if (message && message.type === 'user' && message.isEditing) {
      chatMessageOperations.saveEdit(messageId)
    }
    const { provider, model } = chatModel.getCurrentChatModel()
    chatLogic.resendUserMessage(messageId, messageIndex, provider, model)
  }

  const handleResendUser = (messageId: string, messageIndex: number) => {
    const { provider, model } = chatModel.getCurrentChatModel()
    chatLogic.resendUserMessage(messageId, messageIndex, provider, model)
  }

  return (
    <div
      className="bg-white rounded-lg shadow-sm flex flex-col h-full max-h-full overflow-hidden relative"
      onDragOver={chatAttachments.handleGlobalDragOver}
      onDragEnter={chatAttachments.handleGlobalDragEnter}
      onDragLeave={chatAttachments.handleGlobalDragLeave}
      onDrop={chatAttachments.handleGlobalDrop}
    >
      {/* Chat Header */}
      <ChatHeader
        isStreamMode={chatModel.isStreamMode}
        isGenerating={isGenerating}
        isTyping={isTyping}
        onToggleStream={chatModel.toggleStreamMode}
        onClearChat={handleClearChat}
        onInterrupt={handleInterrupt}
      />

      {/* Chat Messages */}
      <ChatMessageList
        chatContainerRef={chatMessages.chatContainer}
        messages={chatMessagesFromStore}
        renderMarkdown={chatMessages.renderMarkdown}
        renderUserMessage={chatMessages.renderUserMessage}
        chatContainerMaxHeight={chatLogic.chatContainerMaxHeight}
        editingContent={chatMessageOperations.editingContent}
        isTyping={isTyping}
        isGenerating={isGenerating}
        onStartEdit={chatMessageOperations.startEdit}
        onSaveEdit={chatMessageOperations.saveEdit}
        onCancelEdit={chatMessageOperations.cancelEdit}
        onDelete={chatMessageOperations.deleteMessage}
        onCopy={chatMessageOperations.copyMessage}
        onRegenerate={handleRegenerate}
        onResend={handleResend}
        onResendUser={handleResendUser}
        onEditKeydown={chatMessageOperations.handleEditKeydown}
        onSetEditRef={chatMessageOperations.setEditTextareaRef}
        onSetMessageRef={chatMessageOperations.setMessageRef}
        onUpdateEditingContent={chatMessageOperations.updateEditingContent}
      />

      {/* 快速回复选项 */}
      <ChatQuickReplies
        show={chatQuickReplies.shouldShowQuickReplies}
        replies={chatQuickReplies.quickReplies}
        quickRepliesContainerRef={chatQuickReplies.quickRepliesContainerRef}
        inputContainerRef={inputContainerRef}
        onSelect={handleQuickReplySelect}
      />

      {/* Input Area */}
      <div ref={inputContainerRef}>
        <ChatInputArea
          isEditing={chatMessageOperations.isEditing}
          userInput={chatInput.userInput}
          setUserInput={chatInput.setUserInput}
          attachments={chatAttachments.currentAttachments}
          placeholder={chatQuickReplies.shouldShowQuickReplies ? '输入或点击上方快速回复...' : 'Shift+Enter换行'}
          isDisabled={isTyping || isGenerating}
          textareaRef={chatInput.textareaRef}
          showQuickReplies={chatQuickReplies.shouldShowQuickReplies}
          quickReplies={chatQuickReplies.quickReplies}
          quickRepliesContainerRef={chatQuickReplies.quickRepliesContainerRef}
          onKeydown={handleInputKeydown}
          onCompositionStart={chatInput.handleCompositionStart}
          onCompositionEnd={chatInput.handleCompositionEnd}
          onFocus={() => chatQuickReplies.setShowQuickReplies(true)}
          onSend={handleSendMessage}
          onFileSelect={chatAttachments.handleFileSelect}
          onRemoveAttachment={chatAttachments.removeAttachment}
          onClearAttachments={chatAttachments.clearAttachments}
          onQuickReplySelect={handleQuickReplySelect}
          fileInputRef={chatAttachments.fileInputRef}
        />
      </div>
      
      {/* 全局拖拽覆盖层 */}
      {chatAttachments.isGlobalDragging && (
        <div className="absolute inset-0 bg-blue-50 bg-opacity-90 flex items-center justify-center z-50 border-2 border-dashed border-blue-400 rounded-lg">
          <div className="text-center">
            <Upload className="w-12 h-12 mx-auto mb-4 text-blue-500" />
            <div className="text-lg font-medium text-blue-700 mb-2">
              释放文件以上传
            </div>
            <div className="text-sm text-blue-600">
              支持图片、文档、音频等格式
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// src/components/ChatInterface.vue
<template>
  <div
    class="bg-white rounded-lg shadow-sm flex flex-col h-full max-h-full overflow-hidden relative"
    @dragover.prevent="chatAttachments.handleGlobalDragOver"
    @dragenter.prevent="chatAttachments.handleGlobalDragEnter"
    @dragleave.prevent="chatAttachments.handleGlobalDragLeave"
    @drop.prevent="chatAttachments.handleGlobalDrop"
  >
    <!-- Chat Header -->
    <ChatHeader
      :is-stream-mode="chatModel.isStreamMode.value"
      :is-generating="promptStore.isGenerating"
      :is-typing="promptStore.isTyping"
      @toggle-stream="chatModel.toggleStreamMode"
      @clear-chat="chatLogic.clearChat"
      @interrupt="chatLogic.interruptGeneration"
    />

    <!-- Chat Messages -->
    <ChatMessageList
      :chat-container="chatMessages.chatContainer"
      :chat-container-max-height="chatLogic.chatContainerMaxHeight.value"
      :editing-content="chatMessageOperations.editingContent.value"
      @start-edit="chatMessageOperations.startEdit"
      @save-edit="chatMessageOperations.saveEdit"
      @cancel-edit="chatMessageOperations.cancelEdit"
      @delete="chatMessageOperations.deleteMessage"
      @copy="chatMessageOperations.copyMessage"
      @regenerate="handleRegenerate"
      @resend="handleResend"
      @resend-user="handleResendUser"
      @edit-keydown="chatMessageOperations.handleEditKeydown"
      @set-edit-ref="(payload) => chatMessageOperations.setEditTextareaRef(payload.messageId, payload.el)"
      @set-message-ref="chatMessageOperations.setMessageRef"
    />

    <!-- 快速回复选项 -->
    <ChatQuickReplies
      :show="chatQuickReplies.shouldShowQuickReplies.value"
      :replies="chatQuickReplies.quickReplies.value"
      :quick-replies-container="chatQuickReplies.quickRepliesContainer"
      :input-container-ref="inputContainer"
      @select="handleQuickReplySelect"
    />

    <!-- Input Area -->
    <ChatInputArea
      :is-editing="chatMessageOperations.isEditing.value"
      v-model:user-input="chatInput.userInput.value"
      :attachments="chatAttachments.currentAttachments.value"
      :placeholder="chatQuickReplies.shouldShowQuickReplies.value ? '输入或点击上方快速回复...' : 'Shift+Enter换行'"
      :is-disabled="promptStore.isTyping || promptStore.isGenerating"
      :textarea-ref="chatInput.textareaRef.value"
      :input-container="inputContainer"
      :show-quick-replies="chatQuickReplies.shouldShowQuickReplies.value"
      :quick-replies="chatQuickReplies.quickReplies.value"
      :quick-replies-container="chatQuickReplies.quickRepliesContainer"
      @keydown="handleInputKeydown"
      @composition-start="chatInput.handleCompositionStart"
      @composition-end="chatInput.handleCompositionEnd"
      @focus="chatQuickReplies.showQuickReplies.value = true"
      @send="handleSendMessage"
      @file-select="chatAttachments.handleFileSelect"
      @remove-attachment="chatAttachments.removeAttachment"
      @clear-attachments="chatAttachments.clearAttachments"
      @quick-reply-select="handleQuickReplySelect"
    />
    
    <!-- 全局拖拽覆盖层 -->
    <div
      v-if="chatAttachments.isGlobalDragging.value"
      class="absolute inset-0 bg-blue-50 bg-opacity-90 flex items-center justify-center z-50 border-2 border-dashed border-blue-400 rounded-lg"
    >
      <div class="text-center">
        <Upload class="w-12 h-12 mx-auto mb-4 text-blue-500" />
        <div class="text-lg font-medium text-blue-700 mb-2">
          释放文件以上传
        </div>
        <div class="text-sm text-blue-600">
          支持图片、文档、音频等格式
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { usePromptStore } from '@/stores/promptStore'
import { Upload } from 'lucide-vue-next'

// Import components
import ChatHeader from '@/components/chat/components/ChatHeader.vue'
import ChatMessageList from '@/components/chat/components/ChatMessageList.vue'
import ChatQuickReplies from '@/components/chat/components/ChatQuickReplies.vue'
import ChatInputArea from '@/components/chat/components/ChatInputArea.vue'

// Import composables
import { useChatMessages } from '@/components/chat/composables/useChatMessages'
import { useChatInput } from '@/components/chat/composables/useChatInput'
import { useChatAttachments } from '@/components/chat/composables/useChatAttachments'
import { useChatModel } from '@/components/chat/composables/useChatModel'
import { useChatQuickReplies } from '@/components/chat/composables/useChatQuickReplies'
import { useChatMessageOperations } from '@/components/chat/composables/useChatMessageOperations'
import { useChatLogic } from '@/components/chat/composables/useChatLogic'

// Emits
defineEmits<{
  toggle: []
}>()

// Stores
const promptStore = usePromptStore()

// Refs for containers
const inputContainer = ref<HTMLElement>()

// Initialize composables
const chatMessages = useChatMessages()
const chatInput = useChatInput()
const chatAttachments = useChatAttachments()
const chatModel = useChatModel()
const chatQuickReplies = useChatQuickReplies(inputContainer)
const chatMessageOperations = useChatMessageOperations(chatMessages.chatContainer)

const chatLogic = useChatLogic(
  chatMessages,
  chatModel,
  chatInput,
  chatAttachments,
  chatQuickReplies
)

// Event handlers that bridge composables and components
const handleInputKeydown = (event: KeyboardEvent) => {
  chatInput.handleKeydown(event, handleSendMessage)
}

const handleSendMessage = () => {
  chatLogic.sendMessage(chatInput.userInput.value)
}

const handleQuickReplySelect = (reply: string) => {
  chatQuickReplies.selectQuickReply(reply, (selectedReply: string) => {
    chatInput.userInput.value = selectedReply
    handleSendMessage()
  })
}

const handleRegenerate = (payload: { messageId: string, messageIndex: number }) => {
  const { provider, model } = chatModel.getCurrentChatModel()
  chatLogic.regenerateMessage(payload.messageId, payload.messageIndex, provider, model)
}

const handleResend = (payload: { messageId: string, messageIndex: number }) => {
  // Handle resend for edited messages - for user messages in edit mode
  const message = promptStore.chatMessages.find(msg => msg.id === payload.messageId)
  if (message && message.type === 'user') {
    // Save the edit first, then resend
    chatMessageOperations.saveEdit(payload.messageId)
    const { provider, model } = chatModel.getCurrentChatModel()
    chatLogic.resendUserMessage(payload.messageId, payload.messageIndex, provider, model)
  }
}

const handleResendUser = (payload: { messageId: string, messageIndex: number }) => {
  const { provider, model } = chatModel.getCurrentChatModel()
  chatLogic.resendUserMessage(payload.messageId, payload.messageIndex, provider, model)
}

// Initialize chat on mount
onMounted(() => {
  chatLogic.initializeChat()
})
</script>
